### ISSUE TITLE
Something wrong is with Single GPU Passthrough using VFIO directly - releated issue?

### ISSUE THREAD

**Issue by memegauste** [Pavo-IM/Proxintosh#5]
https://github.com/joeknock90/Single-GPU-Passthrough/issues/19

Hi Pavo, I will send to you config later so you will be able to see what I did wrong.
Have nice evening.

**Comment by Pavo-IM** [comment]
This has nothing to do with Proxmox. You are are using Arch

**Comment by memegauste** [comment]
Yes, but maybe you can help me, can you talk with me privately on discord? Will be very thankful for any answers.

**Comment by memegauste** [comment]
https://pastebin.com/yw73gebd
Thats my config, if this will help me, you or anyone to debug the issue.

**Comment by Pavo-IM** [comment]
Take a look at the config.plist I have in this repo and compare each section to yours, you should see some differences. I have seen 3 at least with a quick glance of your config.
