### ISSUE TITLE
Vega GPU Reboot Bug

### ISSUE THREAD

**Issue by trisongz** [Pavo-IM/Proxintosh#6]
Hey Pavo,

I noticed that you have a Radeon VII and in some of your earlier commits, there were parts of the script that modified the proxmox kernel to address the Vega bug, but was later removed. I started this process originally using 2x E5-2860v2s but after failing to get it to work with all methods (modified VM using your method from this repo, as well as vanilla (OC, Clover)) - I gave up and bit the bullet to get the TR 3970X. My specs will be almost identical except that I'll be using the AMD Vega FE instead, and ASRock Creator.

During my other unsuccessful attempts, I had gotten close with it, but the single GPU was power looping on launching the VM, even after adding the specific Vega patches and building the proxmox kernel and init/detach scripts.

Did you have to do anything now to address this issue or was this resolved by the proxmox kernel?

**Comment by Pavo-IM** [comment]
I haven't been successful with using the reset patch on my GPU, I just live with rebooting the entire system after every shutdown of my VM. Also AsRock Creator is a very painful in getting running, make sure you have the latest BIOS that has AGRESA 1.0.0.4 or you gonna have all kinds of issues.

**Comment by trisongz** [comment]
Thanks for that heads up. I would've probably spent hours or days figuring that out. I'm planning on using your Big Sur as a fresh install. When looking at the config.plist on BS, it uses MPro7,1 with a few different settings than the default config.plist you provide. Do you move back to the non-BS config.plist after install or do you keep those settings and migrate the Kexts over?

**Comment by Pavo-IM** [comment]
You have to use the use the BS config.
